[Kaka0 adult] 장바구니 리스트 get method 구현
wecode-bootcamp-korea/21-1st-KaKa0Adult-backend pull request #10
Opened 2021-06-15 02:00 UTC by hyo-jin-jeong

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장바구니 리스트 get method 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 장바구니 리스트 get method 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 예외처리 해야 할 부분이 있을까요?
- user 장바구니가 없으면 생성해서 빈리스트를 보내주어야 하고, 있으면 get 해야해서 get_or_create 메소드를 사용하였습니다. 
request.user.order_set해서 장바구니가 있는지 확인하고 create를 하는 방식이 더 좋을까요?
<img width="417" alt="스크린샷 2021-06-15 오전 10 58 33" src="https://user-images.githubusercontent.com/55984573/121981450-a2001600-cdc8-11eb-9234-a9afe31736ed.png">

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-15 02:30 UTC, Kang-kyunghun requested changes

2021-06-15 02:30 UTC, Kang-kyunghun commented on db_uploader.py
> +        create_table_records()
db_uploader 파일은 제거하고 gitignore에 추가해 주세요.

2021-06-15 02:30 UTC, Kang-kyunghun commented on orders/urls.py
> +    path('/order-items', BasketView.as_view()),
위에 똑같은 endpoint가 존재하는 것 같은데 확인해 주세요.

2021-06-15 02:30 UTC, Kang-kyunghun commented on orders/views.py
> +        )
조회 기능인데, create를 하는 이유가 무엇일까요?

2021-06-15 02:30 UTC, Kang-kyunghun commented on orders/views.py
> +            }for order_item in order.orderitem_set.all()]
```suggestion
            }for order_item in OrderItem.objects.filter(조건)]
```
결국 저희는 OrderItem 중에 장바구니 조건을 만족하는 제품들을 보여주는 것이므로 위와 같이 수정하면 좋을 것 같아요

2021-06-15 02:30 UTC, Kang-kyunghun commented on orders/views.py
> +
공백 제거해 주세요.

2021-06-15 12:33 UTC, hyo-jin-jeong commented on db_uploader.py
> +        create_table_records()
수정했습니다!

2021-06-15 12:33 UTC, hyo-jin-jeong commented on orders/urls.py
> +    path('/order-items', BasketView.as_view()),
수정했습니다!

2021-06-15 12:33 UTC, hyo-jin-jeong commented on orders/views.py
> +        )
수정했습니다!

2021-06-15 12:33 UTC, hyo-jin-jeong commented on orders/views.py
> +            }for order_item in order.orderitem_set.all()]
수정했습니다!

2021-06-15 12:34 UTC, hyo-jin-jeong commented on orders/views.py
> +
수정했습니다!

2021-06-16 01:26 UTC, Kang-kyunghun commented on orders/views.py
> +                'image_url'    : order_item.product.imageurl_set.order_by('id')[0].url,
대표이미지(썸네일) 같은 경우는 product에 컬럼을 만들어서 사용하는 것도 좋은 방법 중 하나 입니다.
그러면 대표 이미지의 정보를 얻기 위해서 역참조를 안 하고 바로 product 테이블에서 가져 올 수 있습니다.
이거는 일단 참고 사항이니 당장 수정하지 않으셔도 됩니다.

2021-06-16 01:27 UTC, Kang-kyunghun commented
LGTM~!!

2021-06-16 01:27 UTC, merged