add: 로그인 기능 구현 및 데코레이터구현(실험완료)
wecode-bootcamp-korea/21-1st-KaKa0Adult-backend pull request #5
Opened 2021-06-10 09:34 UTC by dlwjdals5600

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 기능 구현 및 데코레이터 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 로그인을 할 때 데이터베이스상에서 이메일이 존재하지 않을 시 오류401 리턴
- bcrypt.checkpw를 이용해서 암호화된 비밀번호 검사 후 틀리다면 오류401 리턴
- users앱에 utils.py를 만들어서 데코레이터 구현(다른 뷰를 만들어서 잘 작동하는지 확인 완료, runserver도 문제 없음)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 브랜치를 기능별로 따야하는데 로그인을 구현하면서 같은팀원들의 기능을 위해 데코레이터를 같이 구현할지 연우 멘토님께 질문을 했는데 같이 구현하는게 맞다고 하셔서 같이 구현하였습니다. 그때 말씀하셨던 기능별로 브랜치를 따야한다고 말씀을 하셔서 잘 한 것인지 여쭤보려고 글을 올립니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-10 11:06 UTC, Kang-kyunghun requested changes

2021-06-10 11:06 UTC, Kang-kyunghun commented on users/utils.py
> +from users.models        import User
import 라인 맞춰 주세요.

2021-06-10 11:06 UTC, Kang-kyunghun commented on users/views.py
> +from kaka0Adult.settings import SECRET_KEY, ALGORITHM
import 라인 맞춰 주세요.

2021-06-10 11:06 UTC, Kang-kyunghun commented on users/views.py
> +                return JsonResponse({'message':'PASSWORD_INCORRECT'},status=401)
'사용자가 존재하지 않을 때' 와 '존재는 하지만 비밀번호는 틀렸을 때'를 구분하여 에러메세지를 전달하면, 보안에 취약할 수 있습니다. 제3자가 이메일을 알아내어, 비밀번호만 계속 바꿔가며 해킹을 시도할 때에 힌트를 주는 격이 됩니다 🙂  따라서, 보다 안전한 서비스를 만들기 위하여 두 경우의 에러메세지와 에러 코드를 통일시키는 것을 추천드립니다.

2021-06-10 11:21 UTC, dlwjdals5600 commented on users/utils.py
> +from users.models        import User
CRUD세션중에 승현님께서 import줄맞춤을 할 때 나중에 import들이 많이 늘어나면 더러워보일 수 있다고 말씀하시면서 파이썬 자체 모듈, django, 내가 사용한 import들을 각각 따로 줄맞춤을 하는게 좋다고 지나가면서 말씀을 하셨는데 어떤 방식이 정공법인지 궁금합니다. 고치는게 나을까요???

2021-06-10 11:22 UTC, dlwjdals5600 commented on users/views.py
> +                return JsonResponse({'message':'PASSWORD_INCORRECT'},status=401)
네! 보안상 생각을 못했던 것 같습니다. 수정 완료하였습니다. 감사합니다!!

2021-06-10 11:28 UTC, dlwjdals5600 commented on users/utils.py
> +from users.models        import User
<img width="597" alt="스크린샷 2021-06-10 오후 8 26 03" src="https://user-images.githubusercontent.com/78079712/121517488-63fe9d00-ca2a-11eb-8dd1-1265b59a40a2.png">

2021-06-11 01:51 UTC, Kang-kyunghun commented on users/utils.py
> +from users.models        import User
제가 너무 두서 없이 라인을 맞추라고 했네요.
일단 import 라인을 맞추는 것은 wecode의 컨벤션이기 때문에 정공법은 없습니다. 저희가 import 라인을 맞추는 이유는 가독성을 위해서 입니다. 그래서 승현님이 말씀하신 것처럼 '나중에 import들이 많이 늘어나면 더러워보일 수 있기 때문에 위와 같이 하셨다면 잘 하셨습니다. 
그런데 제가 import 라인 통일 시키라고 했던 이유는 더러워 보이는 상황이 아니여서 코멘트를 남겼던 것입니다. 
이유가 있다고 한다면, 굳이 수정 안 하셔도 괜찮습니다.

2021-06-11 01:52 UTC, Kang-kyunghun commented
PR의 제목은 처음 PR 올렸을 때 무엇을 위한 PR인지 나타내고 되도록 수정하지 않습니다.
수정된 내용이나 리뷰어가 알아야 하는 내용은 PR template과 코멘트를 활용해 주세요.

2021-06-11 01:53 UTC, dlwjdals5600 commented on users/utils.py
> +from users.models        import User
자세하게 알려주셔서 감사합니다!!

2021-06-11 03:18 UTC, Kang-kyunghun commented
고생 하셨습니다~~ 💯

2021-06-11 03:18 UTC, merged