[kaka0 Adult] ProductView 완료
wecode-bootcamp-korea/21-1st-KaKa0Adult-backend pull request #7
Opened 2021-06-11 06:56 UTC by jotasic

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 상품 조회 기능 추가
		 
## 수정 사항들 자세한 내용
- 쿼리 스트링에 따라 상품 결과가 반환 되도록 기능 추가함.

/products?`type`=타입명&`keyword`=키워드&`pageSize`=페이지사이즈&`page`=페이지번호
- type : 필터링 타입 new,hot,search,category,character가 값으로 올 수 있음
    - new : 신상품 순 => keyword 필요없음
    - hot : 좋아요가 많은 수 => keyword 필요없음
    - search : 제품명으로 검색시 => keyword : 상품명
    - category : 카테고리명으로 검색 시 => keyword : 카테고리명
    - character : 캐릭터명으로 검색 시 => keyword : 캐릭터명
- keyword : 필터링 타입에 따른 검색 키워드
- pageSize : 페이지 사이즈 한번 요청시 받아올 결과 갯수
- page : 현재 페이지
- pageSize 와 page를 포함 시키지 않으면 전체 결과를 반환함

요청 결과 예시(백 -> 프)
```json
{
    "resultList": [
        {
            "id": 90,
            "name": "[마지막기회] 신소재 앵무새 집",
            "price": "82500.000",
            "stock": true,
            "like": false,
            "cart": false,
            "image": "https://i.picsum.photos/id/866/256/256.jpg?ramdom=1"
        },
        {
            "id": 89,
            "name": "[마지막기회] 신소재 고슴도치 집",
            "price": "83100.000",
            "stock": true,
            "like": false,
            "cart": false,
            "image": "https://i.picsum.photos/id/866/256/256.jpg?ramdom=1"
        }
    ],
    "page": 1,
    "pageSize": 2,
    "totalCount": 90,
    "totalPageCount": 45,
    "numberOfElements": 2
}
```

1. resultList : 결과 리스트
    - id : 상품 id값
    - name : 상품 이름
    - price : 상품 가격
    - stock : 재고 여부
    - like : 좋아요 여부
    - cart : 장바구니 여부
    - image : 대표이미지 url

2.  page : 현재 페이지 번호
3. pageSize : 페이지 한개당 결과 갯수
4. totalCount : 전체 아이템 갯수
5. totalPageCount : 전체 페이지 갯수
6. numberOfElements : 결과 리스트의 길이

**page와 pageSize를 쿼리파라미터로 넘기지 않으면 전체 결과를 반환하고, `page`, `pageSize`, `totalPageCount`를 결과에 포함시키지 않도록 함**

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
1. like수가 많은 순서대로 product를 얻고 싶어서 group by를 사용하여 count를 이용해서 했습니다.
   - 하지만 무조건 values를 사용해야되서 쿼리셋으로 반환 받지 못하였습니다
   - 그래서 like수가 많은순으로 product id를 list로 받은 후, 스텍 오버플로우 참고하여 조건에 맞게 정렬된 쿼리셋을 가져오도록 하였는데, 다른 방법이 있을 지 궁금합니다. 

2. 쿼리스트링 중에 type에 잘못된 값이 들어왔을 때, 빈 list를 반환, 입력을 안 했을시에는 모든 상품을 반환하도록 하였는데, 이렇게 처리하는 것이 괜찮은지 궁금합니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-14 01:53 UTC, Kang-kyunghun requested changes

2021-06-14 01:53 UTC, Kang-kyunghun commented on products/views.py
> +    @login_decorator
좋아요 때문에 로그인 데코레이터를 사용하신 건가요?

2021-06-14 01:53 UTC, Kang-kyunghun commented on products/views.py
> +        page_size    = int(request.GET.get('pageSize', 0))
페이지네이션을 위한 offset과 limit로 보입니다. 만약에 페이지네이션을 사용될 값이 프론트에서 안 들어 온다면, default로 넘겨줄 offset과 limit를 미리 정해 주면 아래 로직이 더 간단해 집니다.

2021-06-14 01:53 UTC, Kang-kyunghun commented on products/views.py
> +
필터링 부분은 저랑 구두로 한 번 이야기 할게요~

2021-06-14 02:10 UTC, jotasic commented on products/views.py
> +    @login_decorator
저희가 로그인이 안되었을 때, main페이지로 진입이 안되게 하도록 하였기 때문에, 로그인 데코레이터 사용하였습니다.

2021-06-14 11:16 UTC, jotasic commented on products/views.py
> +        page_size    = int(request.GET.get('pageSize', 0))
구두로 말씀하신대로 프론트에서 페지네이션을 사용하지 않아도 기본 값(0)을 받는 것은 이해를 하였는데,
로직이 간단해 진다는 이해를 하지 못한것 같습니다. 지금도 프론트에서 해당값을 주지않으면, 0값으로 사용하기 때문입니다

2021-06-14 11:17 UTC, jotasic commented on products/views.py
> +
필터링 말씀하신 사항 1차 수정 완료하였습니다.

2021-06-14 15:08 UTC, Kang-kyunghun requested changes

2021-06-14 15:08 UTC, Kang-kyunghun commented on products/views.py
> +        filter_conditions   = Q()
```suggestion
        q   = Q()
```
Q()을 사용할 때 위와 같이 소문자 q에 Q()를 담는 것이 암묵적인 방법입니다. 당연히 어떤 변수에 넣어도 상관 없지만, 협업하는 입장에서 장고에서 암묵적으로 가져가는 룰은 지키는 것이 좋다고 생각합니다.

2021-06-14 15:08 UTC, Kang-kyunghun commented on products/views.py
> +                order__order_status__status=OrderStatus.BASKET).exists(),
```suggestion
            'cart'  : product.orderitem_set.filter(
                order__user = user,
                order__order_status__status=OrderStatus.BASKET).exists(),
```
- filter()을 사용할 경우 앞에 all()을 사용하지 않아도 됩니다.
- user는 request로부터 얻기 때문에 굳이 id까지 안 가도 될 것 같습니다.

2021-06-14 15:08 UTC, Kang-kyunghun commented on products/views.py
> +            'image' : product.imageurl_set.order_by('id')[0].url
이미지는 무조건 하나만 존재하나요? 1장만 보내는 이유가 있을까요?

2021-06-14 15:08 UTC, Kang-kyunghun commented on products/views.py
> +        result['numberOfElements'] = filtered_products.count()
2개의 데이터가 같은 것 같은데, 아니라면 설명 코멘트 부탁드립니다.

2021-06-14 15:08 UTC, Kang-kyunghun commented on products/views.py
> +                *order_conditions)
```suggestion
        filtered_products = Product.objects.filter(q)
                                   .annotate(like_count=Count(like__product_id)
                                   .order_by(-'created_at')
```
1. like count는 조건에 상관없이 annotate를 해도 무방할 것으로 보입니다.
2. order_by 조건이 create_at 밖에 없으므로 마지막에 한 번 사용해 주면 좋을 것 같습니다.

2021-06-14 15:09 UTC, Kang-kyunghun commented on products/views.py
> +        page_size    = int(request.GET.get('pageSize', 0))
전부를 다 줘야 한다는 설명을 듣기 전에 남긴 코멘트 입니다.

2021-06-14 15:12 UTC, Kang-kyunghun commented
중복 필터링이 존재하지 않는다면 현재보다 간단히 바꿀수 있을 것 같은데, 오전에 일찍 같이 코드 보면서 얘기하면 좋을 것 같습니다.

2021-06-14 23:04 UTC, jotasic commented on products/views.py
> +            'image' : product.imageurl_set.order_by('id')[0].url
네 제품목록 페이지의 경우 이미지 중 1개만 표시되고,
상세페이지에서는 모든 이미지가 필요합니다.

2021-06-14 23:13 UTC, jotasic commented on products/views.py
> +        result['numberOfElements'] = filtered_products.count()
totalCount : 해당 조건으로 검색시 전체 데이터 개수 입니다.
numberOfElements : 반환하는 상품정보에 대한 갯수입니다. 일반적으로 pageSize와 동일하겠지만 마지막 페이지에서는 달라질 수 있습니다.

ex) 최신 상품순으로 검색시 전체 data가 11개가 될 시에 `totalCount`는 11개 입니다.
만약 이 조건에서 `pageSize`가 10 일 경우 2번째 page 에서는 `numberOfElements`는 1이 됩니다.

2021-06-14 23:15 UTC, jotasic commented on products/views.py
> +                *order_conditions)
> like count는 조건에 상관없이 annotate를 해도 무방할 것으로 보입니다

어짜피 hot일때 말고 count를 사용해서 정렬을 하지 않으니 상관 없군요!

> order_by 조건이 create_at 밖에 없으므로 마지막에 한 번 사용해 주면 좋을 것 같습니다

type의 잘못된 option이 들어올 시에 안하도록 하고 싶었는데, 너무 깊은 생각이였던것 같습니다.!

2021-06-14 23:18 UTC, jotasic commented on products/views.py
> +        filter_conditions   = Q()
수정 완료했습니다

2021-06-14 23:18 UTC, jotasic commented on products/views.py
> +    @login_decorator
이 부분은 저희 팀원분들과 다시 말해봤는데, 이대로 진행될 것 같습니다.

2021-06-14 23:20 UTC, jotasic commented on products/views.py
> +                order__order_status__status=OrderStatus.BASKET).exists(),
수정완료하였습니다.

2021-06-15 00:41 UTC, jotasic commented
> 중복 필터링이 존재하지 않는다면 현재보다 간단히 바꿀수 있을 것 같은데, 오전에 일찍 같이 코드 보면서 얘기하면 좋을 것 같습니다.

2021-06-15 23:36 UTC, jotasic commented
제가 어제 이야기 한것에 생각을 못하고 맞다고 해서 혼동이 왔습니다. 

 기존에 이렇게 되어 있는 코드를
```python
Product.objects.filter(q).annotate(like_count=Count(like__product_id).order_by(-'created_at')
```

이러한 방식으로 수정하라고 피드백 받았는데 그 당시에는 맞는 것 같았으나, 막상 구현을 하려보니
저 필터의 q.get()을 할 때 쓸 키값을 어디서 구해야될지가 잘 안됩니다.

```python
Product.objects.filter(q.get(type, Q())).annotate(like_count=Count(like__product_id).order_by(-'created_at')
```
또한 어제 생각해보니 구현해야되는 조건 자체는 or이지만 and로 구현하면 나중에 더 유연할 것 같다라는 생각이 드는데,

어떻게 생각하시나요?

이점에 대해서 도움을 드립니다.

2021-06-16 02:15 UTC, jotasic commented
필터링 관련해서 피드백 받은대로 수정하였습니다.

제가 초기에 질문드린 내용은 search, category, character 중 1개의 조건만을 사용해야 되야되는 상황으로 질문드려 피드백을 주셨는데, 피드백 주신 내용을 바탕으로 계속 구조를 바꿔가니 search, category, character의 조건을 and로 하는 것이 기존 기획을 유지하면서 구조적으로 더 유연해진다는 것을 알게되어 좋았습니다.

감사합니다!!

2021-06-16 05:21 UTC, Kang-kyunghun commented
고생 많으셨습니다~~!!!!!

2021-06-16 05:22 UTC, merged