[kaka0 Adult] LikeView 좋아요 기능 추가
wecode-bootcamp-korea/21-1st-KaKa0Adult-backend pull request #9
Opened 2021-06-15 01:59 UTC by dlwjdals5600

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 좋아요 기능 구현
- urls.py에서 import 제거
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 좋아요 기능 추가(좋아요 추가 post / 좋아요 제거 delete)
- post로 요청 받을 때는 product_id를 body에 받고, 데코레이터의 유저 정보를 이용하여 like테이블에 존재하지 않을 때 create시켜 줌
- delete로 요청 받을 때는 url파라미터로 product_id를 받고, 데코레이터의 우저 정보를 이용하여 like테이블에 존재하면 delete시켜 줌
- 효진님 order를 pull받고 migrate했을 때 오류가 나서 urls.py에서 사용하지 않는 import제거(migrate 완료)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
프론트 분들과 서로 구현한 것들을 붙이는 과정에서 '좋아요'를 여러가지 방법으로 구현할 수 있어서 좋았던것 같습니다.(힘들었지만...)
이 과정에서 오류가 많이 뜨고 고치는 과정중에서 프론트와 저희 서버의 관계를 많이 알 수 있는 계기가 되었던 것 같습니다.(유익한 시간인듯)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-15 13:21 UTC, Kang-kyunghun requested changes

2021-06-15 13:21 UTC, Kang-kyunghun commented on users/views.py
> +                Q(user_id = request.user.id)|
| 조건이면 해당 유저와 product의 모든 좋아요를 삭제할 것 같습니다. 확인해 주세요.

2021-06-15 13:21 UTC, Kang-kyunghun commented on users/views.py
> +
공백 제거해 주세요.

2021-06-15 13:21 UTC, Kang-kyunghun commented on users/views.py
> +            product_id = data['product_id']
```suggestion
            data       = json.loads(request.body)
            product_id = data['product_id']
            user       = request.user
```
- =을 기준으로 정렬해 주세요.
- request.user를 밑에서 자주 사용하므로 변수에 담아서 사용해도 좋을 거 같아요

2021-06-15 13:21 UTC, Kang-kyunghun commented on users/views.py
> +                product_id = product_id).exists():
```suggestion
            if not Like.objects.filter(user=user, product_id = product_id).exists():
```
- 굳이 줄을 바꾸지 않아도 될 것 같아요. 오히려 줄을 바꿔서 가독성이 떨어지는 것 같습니다.
- request.user로 user을 알 수 있기 때문에 user_id 대신에 user로 바로 받아도 됩니다.

2021-06-15 13:21 UTC, Kang-kyunghun commented on users/views.py
> +
공백은 1줄만 해주세요.

2021-06-16 01:31 UTC, dlwjdals5600 commented on users/views.py
> +                Q(user_id = request.user.id)|
경훈님 말씀대로 'or' 사용해버려서 삭제하면 한번에 다 날라갔던것 같습니다. ,(and)로 고쳐서 지정한 1개만 삭제되게 되었습니다.

2021-06-16 01:31 UTC, dlwjdals5600 commented on users/views.py
> +
공백 제거 완료 했습니다.

2021-06-16 01:32 UTC, dlwjdals5600 commented on users/views.py
> +            product_id = data['product_id']
= 기준으로 정렬 했습니다.
user = request.user를 사용했습니다.

2021-06-16 01:37 UTC, dlwjdals5600 commented on users/views.py
> +                product_id = product_id).exists():
한줄로 바꾸시라고 한 것은 filter()안에 user=user등 값들이 2개 밖에 없어서 한줄로 봐도 한번에 볼 수 있어서 바꾸라고 한건지 궁금합니다.
(만약에 여러개의 매개변수들이 들어간다고 한다면 줄바꿈을 사용하는 것이 좋은것이겠죠??)

user=request.user를 사용해서 user = user.id를 만드니깐 
ValueError: Cannot assign "13": "Like.user" must be a "User" instance. 라는 오류가 떠서 그대로 user_id를 그대로 사용하였습니다.

2021-06-16 01:38 UTC, dlwjdals5600 commented on users/views.py
> +
넵! 수정 완료했습니다.

2021-06-16 05:27 UTC, Kang-kyunghun requested changes

2021-06-16 05:27 UTC, Kang-kyunghun commented on users/views.py
> +        return JsonResponse({'message':'DELETE_SUCCESS'}, status=204)
filter을 이용해서 delete을 지운다면 조건문이 없어도 되지 않을까요? 존재하지 않으면 filter에 의해 빈 쿼리셋이 나오고 빈쿼리셋을 delete하는 것은 아무 영향이 없을 것 같은데, 어떻게 생각하시나요? 
의견 코멘트로 남겨주세요.

2021-06-16 06:00 UTC, dlwjdals5600 commented on users/views.py
> +        return JsonResponse({'message':'DELETE_SUCCESS'}, status=204)
경훈님의 PR을 보고 멱등성에 대해서 알아보았는데 create같은 경우는 계속 똑같은게 만들어질 수 있기 때문에 if문을 써야하지만 delete같은 경우는 이미 존재하든, 존재하지 않든 그 데이터는 delete요청을 보낸 시점에서 사라지게 되기 때문에 if문을 사용할 필요가 없다는 것을 알게 되었습니다.
(delete에서 if문을 제거 완료했습니다.)

2021-06-16 06:11 UTC, Kang-kyunghun commented
고생 많으셨습니다~~ LGTM!

2021-06-16 06:11 UTC, merged